AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: User registration (Cognito post-confirmation hook + DynamoDB persistence)

Parameters:
  StackNameSuffix:
    Type: String
    Default: user-registration
  UsersTableName:
    Type: String
    Default: UsersTable
    Description: DynamoDB table name for storing user profiles
  OrganizationsTableName:
    Type: String
    Default: OrganizationsTable
    Description: DynamoDB table name for storing organization/subscription metadata
  UserPoolName:
    Type: String
    Default: BursaUserPool
    Description: Name for the Cognito User Pool created by this stack
  UserPoolClientName:
    Type: String
    Default: BursaWebClient
    Description: Cognito App Client name created by this stack
  FreeTierGroupName:
    Type: String
    Default: Free-Tier
    Description: Cognito group assigned to new users
  DefaultLanguage:
    Type: String
    Default: he
    AllowedValues: [ en, he ]
    Description: Default language preference for newly created users
  Tier1Limit:
    Type: Number
    Default: 5
    Description: Monthly Tier 1 credit allowance for free accounts
  Tier2Limit:
    Type: Number
    Default: 3
    Description: Monthly Tier 2 credit allowance for free accounts
  WelcomePeriodDays:
    Type: Number
    Default: 30
    Description: Number of days before free-tier welcome credits expire

Globals:
  Function:
    Runtime: python3.12
    Timeout: 15
    MemorySize: 256
    Architectures: [ x86_64 ]
    Environment:
      Variables:
        FREE_TIER_GROUP_NAME: !Ref FreeTierGroupName
        DEFAULT_LANGUAGE: !Ref DefaultLanguage
        FREE_TIER_TIER1_LIMIT: !Ref Tier1Limit
        FREE_TIER_TIER2_LIMIT: !Ref Tier2Limit
        FREE_TIER_WELCOME_DAYS: !Ref WelcomePeriodDays

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref UsersTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  OrganizationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref OrganizationsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: organizationId
          AttributeType: S
      KeySchema:
        - AttributeName: organizationId
          KeyType: HASH

  PostConfirmationRegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "--post-confirmation"
      CodeUri: ../user_registration_lambda
      Handler: user_registration.lambdas.post_confirmation.lambda_handler
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref UsersTable
          ORGS_TABLE_NAME: !Ref OrganizationsTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource:
                - !GetAtt UsersTable.Arn
                - !GetAtt OrganizationsTable.Arn
            - Effect: Allow
              Action:
                - cognito-idp:AdminAddUserToGroup
              Resource: !Sub arn:aws:cognito-idp:::userpool/

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      LambdaConfig:
        PostConfirmation: !GetAtt PostConfirmationRegistrationFunction.Arn
      AutoVerifiedAttributes: [ email ]
      Schema:
        - Name: email
          Required: true
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Ref UserPoolClientName
      GenerateSecret: false

  FreeTierGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: !Ref FreeTierGroupName
      UserPoolId: !Ref UserPool
      Description: Default group for free-tier users

Outputs:
  FunctionName:
    Description: Name of the post-confirmation registration Lambda function
    Value: !Ref PostConfirmationRegistrationFunction
  UserPoolIdOutput:
    Description: Cognito User Pool created by this stack
    Value: !Ref UserPool
  UserPoolClientId:
    Description: Cognito App Client identifier
    Value: !Ref UserPoolClient
  UsersTableOutput:
    Description: Name of the created Users DynamoDB table
    Value: !Ref UsersTable
  OrganizationsTableOutput:
    Description: Name of the created Organizations DynamoDB table
    Value: !Ref OrganizationsTable
  FreeTierGroupNameOutput:
    Description: Cognito group name assigned to new users
    Value: !Ref FreeTierGroupName
