version = 0.1

[default.deploy.parameters]
stack_name = "bursa-nlq-backend"
resolve_s3 = true
s3_prefix = "bursa-nlq-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "StageName=\"prod\" AllowedOrigin=\"https://main.dfwhu4l3em50s.amplifyapp.com\" DynamoTableName=\"CompanyDisclosuresHebrew\""
image_repositories = []
