name: Build & Push Backend to ECR

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1                # <-- your region
      ECR_REPO: bursa-nlq-backend          # <-- your ECR repo name (lowercase)
      IMAGE_TAG: latest                    # App Runner can track :latest
    steps:
      - uses: actions/checkout@v4

      # Configure AWS creds via OIDC (no long-lived secrets)
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::241579295267:role/GHA_ECR_PUSH_ROLE
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Get ECR URI
        id: ecr
        run: |
          echo "uri=$(aws ecr describe-repositories \
            --repository-names $ECR_REPO \
            --region $AWS_REGION \
            --query 'repositories[0].repositoryUri' \
            --output text)" >> $GITHUB_OUTPUT

      - name: Build & push
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG backend
          docker tag  $ECR_REPO:$IMAGE_TAG ${{ steps.ecr.outputs.uri }}:$IMAGE_TAG
          docker push ${{ steps.ecr.outputs.uri }}:$IMAGE_TAG
